/* This file was automatically generated by CasADi 3.6.3+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int fun_obj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int fun_obj_alloc_mem(void);
int fun_obj_init_mem(int mem);
void fun_obj_free_mem(int mem);
int fun_obj_checkout(void);
void fun_obj_release(int mem);
void fun_obj_incref(void);
void fun_obj_decref(void);
casadi_int fun_obj_n_in(void);
casadi_int fun_obj_n_out(void);
casadi_real fun_obj_default_in(casadi_int i);
const char* fun_obj_name_in(casadi_int i);
const char* fun_obj_name_out(casadi_int i);
const casadi_int* fun_obj_sparsity_in(casadi_int i);
const casadi_int* fun_obj_sparsity_out(casadi_int i);
int fun_obj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define fun_obj_SZ_ARG 2
#define fun_obj_SZ_RES 1
#define fun_obj_SZ_IW 0
#define fun_obj_SZ_W 3
int fun_obj_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int fun_obj_grad_alloc_mem(void);
int fun_obj_grad_init_mem(int mem);
void fun_obj_grad_free_mem(int mem);
int fun_obj_grad_checkout(void);
void fun_obj_grad_release(int mem);
void fun_obj_grad_incref(void);
void fun_obj_grad_decref(void);
casadi_int fun_obj_grad_n_in(void);
casadi_int fun_obj_grad_n_out(void);
casadi_real fun_obj_grad_default_in(casadi_int i);
const char* fun_obj_grad_name_in(casadi_int i);
const char* fun_obj_grad_name_out(casadi_int i);
const casadi_int* fun_obj_grad_sparsity_in(casadi_int i);
const casadi_int* fun_obj_grad_sparsity_out(casadi_int i);
int fun_obj_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define fun_obj_grad_SZ_ARG 2
#define fun_obj_grad_SZ_RES 1
#define fun_obj_grad_SZ_IW 0
#define fun_obj_grad_SZ_W 2
#ifdef __cplusplus
} /* extern "C" */
#endif
